defaultEntryPoints = ["https"]

[entryPoints]
    [entryPoints.http]
    address = ":80"
      [entryPoints.http.redirect]
        entryPoint = "https"
    [entryPoints.https]
    address = ":443"
    [[entryPoints.https.tls.certificates]]
    CertFile = "/etc/traefik-ssl/fullchain.pem"
    KeyFile = "/etc/traefik-ssl/privkey.pem"
